title: Aplicación móvil (PWA) para empleados
description: Documentación de la aplicación móvil (PWA) para empleados de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/control-de-accesos"
